// Illustrative planning data only. See docs/data.md.
const stop=(id,name,x,y,south,features,values={})=>({id,name,x,y,south,features,endpoint:true,hotel:6,food:6,interest:6,...values});
export const stations=[
stop("sapporo","Sapporo",68,5,-20,["easy-food","arcade","baseball","rainy-day","easy-overnight"],{hotel:10,food:10,interest:9}),
stop("hakodate","Hakodate",64,14,-16,["scenic","seafood","onsen","night-view","easy-overnight"],{hotel:9,food:9,interest:10}),
stop("aomori","Aomori",61,24,-12,["scenic","seafood","apple","railfan","onsen"],{hotel:7,food:8,interest:8}),
stop("akita","Akita",53,30,-9,["goblin","sake","rainy-day","easy-food","railfan"],{hotel:7,food:8,interest:7}),
stop("morioka","Morioka",67,31,-9,["easy-food","noodles","onsen","easy-overnight"],{hotel:7,food:8,interest:7}),
stop("sendai","Sendai",72,40,-5,["baseball","arcade","easy-food","nightlife","easy-overnight"],{hotel:9,food:9,interest:9}),
stop("niigata","Niigata",51,40,-5,["sake","seafood","rainy-day","easy-food","easy-overnight"],{hotel:8,food:9,interest:8}),
stop("yamagata","Yamagata",65,42,-4,["onsen","fruit","quiet","scenic","easy-overnight"],{hotel:7,food:7,interest:7}),
stop("nagano","Nagano",57,47,-2,["onsen","mountains","quiet","scenic","easy-overnight"],{hotel:7,food:7,interest:7}),
stop("kanazawa","Kanazawa",38,49,0,["garden","seafood","coffee","easy-food","rainy-day"],{hotel:8,food:9,interest:9}),
stop("toyama","Toyama",47,42,-1,["scenic","seafood","mountains","railfan","easy-overnight"],{hotel:7,food:7,interest:7}),
stop("fukui","Fukui",34,55,2,["dinosaur","quiet","soba","goblin","easy-overnight"],{hotel:6,food:7,interest:7}),
stop("tsuruga","Tsuruga",30,59,3,["railfan","seafood","goblin","easy-food","easy-overnight"],{hotel:6,food:7,interest:7}),
stop("karuizawa","Karuizawa",61,53,-1,["coffee","scenic","quiet","easy-food","garden"],{hotel:8,food:8,interest:8}),
stop("tokyo","Tokyo",76,54,-3,["arcade","baseball","easy-food","nightlife","garden","easy-overnight"],{hotel:10,food:10,interest:10}),
stop("kamakura","Kamakura",73,61,0,["sea","temple","scenic","coffee","easy-food"],{hotel:7,food:8,interest:10}),
stop("maibara","Maibara",38,65,5,["quiet","railfan"],{hotel:5,food:5,interest:5}),
stop("kyoto","Kyoto",33,70,7,["garden","temple","coffee","easy-food","nightlife"],{hotel:10,food:10,interest:10}),
stop("nara","Nara",36,78,9,["temple","garden","quiet","scenic","easy-food"],{hotel:7,food:7,interest:10}),
stop("osaka","Osaka",27,76,8,["arcade","baseball","easy-food","nightlife","goblin","easy-overnight"],{hotel:10,food:10,interest:10}),
stop("kobe","Kobe",22,78,9,["sea","coffee","night-view","easy-food","baseball"],{hotel:9,food:9,interest:9}),
stop("himeji","Himeji",17,79,10,["castle","garden","easy-food","scenic","easy-overnight"],{hotel:7,food:8,interest:9}),
stop("okayama","Okayama",10,75,11,["garden","castle","easy-food","easy-overnight","railfan"],{hotel:7,food:7,interest:7}),
stop("onomichi","Onomichi",4,78,12,["sea","scenic","goblin","coffee","bike"],{hotel:7,food:8,interest:10}),
stop("takamatsu","Takamatsu",17,89,13,["udon","garden","sea","easy-food","easy-overnight"],{hotel:8,food:9,interest:9}),
stop("kotohira","Kotohira",23,94,15,["onsen","temple","udon","quiet","goblin"],{hotel:7,food:8,interest:9}),
stop("matsuyama","Matsuyama",9,93,15,["onsen","castle","tram","easy-food","easy-overnight"],{hotel:8,food:8,interest:9}),
stop("hiroshima","Hiroshima",3,70,13,["baseball","easy-food","nightlife","easy-overnight","scenic"],{hotel:9,food:9,interest:9}),
stop("miyajimaguchi","Miyajimaguchi",1,75,14,["sea","temple","scenic","oyster","goblin"],{hotel:5,food:8,interest:9}),
stop("kokura","Kokura",2,84,17,["railfan","castle","easy-food","goblin","easy-overnight"],{hotel:8,food:8,interest:8}),
stop("hakata","Hakata",5,90,19,["baseball","ramen","arcade","easy-food","easy-overnight"],{hotel:10,food:10,interest:10}),
stop("nagasaki","Nagasaki",0,98,20,["tram","sea","scenic","coffee","goblin"],{hotel:8,food:8,interest:10}),
stop("kumamoto","Kumamoto",10,99,21,["castle","ramen","garden","easy-food","easy-overnight"],{hotel:8,food:9,interest:9}),
stop("kagoshima","Kagoshima",17,106,23,["volcano","onsen","scenic","ferry","easy-food"],{hotel:8,food:8,interest:10})
];
const edge=(from,to,minutes,headway,line,extras={})=>({from,to,minutes,headway,line,confidence:headway>35?"medium":"high",...extras});
const pair=(a,b,minutes,headway,line,extras)=>[edge(a,b,minutes,headway,line,extras),edge(b,a,minutes,headway,line,extras)];
export const services=[
...pair("sapporo","hakodate",230,60,"Limited Express Hokuto",{green:true,scenic:8}),
...pair("hakodate","aomori",70,60,"Hokkaido / Tohoku Shinkansen",{green:true,scenic:7}),
...pair("aomori","morioka",115,40,"Tohoku Shinkansen",{green:true,scenic:7}),
...pair("morioka","sendai",80,25,"Tohoku Shinkansen",{green:true,scenic:5}),
...pair("sendai","tokyo",95,15,"Tohoku Shinkansen",{green:true,gran:true,scenic:5}),
...pair("akita","morioka",95,60,"Akita Shinkansen",{green:true,scenic:8,railfan:4}),
...pair("yamagata","sendai",75,60,"Senzan Line",{green:false,scenic:8,railfan:4}),
...pair("niigata","tokyo",120,20,"Joetsu Shinkansen",{green:true,scenic:5}),
...pair("nagano","karuizawa",30,30,"Hokuriku Shinkansen",{green:true,scenic:6}),
...pair("karuizawa","tokyo",65,30,"Hokuriku Shinkansen",{green:true,gran:true,scenic:5}),
...pair("kanazawa","toyama",22,20,"Hokuriku Shinkansen",{green:true,scenic:4}),
...pair("kanazawa","tsuruga",55,30,"Hokuriku Shinkansen",{green:true,scenic:6}),
...pair("kanazawa","nagano",65,30,"Hokuriku Shinkansen",{green:true,scenic:6}),
...pair("kanazawa","tokyo",155,30,"Hokuriku Shinkansen",{green:true,gran:true,scenic:7}),
...pair("tsuruga","fukui",18,30,"Hokuriku Shinkansen",{green:true,scenic:4}),
...pair("tsuruga","maibara",52,30,"Limited Express",{green:true,scenic:6}),
...pair("maibara","kyoto",20,15,"Tokaido Shinkansen",{green:true,scenic:3}),
...pair("kyoto","osaka",28,15,"JR Kyoto Line",{green:false,scenic:3}),
...pair("kyoto","nara",48,30,"Nara Line",{green:false,scenic:4}),
...pair("osaka","kobe",22,15,"JR Kobe Line",{green:false,scenic:4}),
...pair("osaka","himeji",60,15,"Sanyo Shinkansen",{green:true,scenic:5}),
...pair("himeji","okayama",22,20,"Sanyo Shinkansen",{green:true,scenic:5}),
...pair("okayama","onomichi",65,30,"Sanyo Main Line",{green:false,scenic:8,railfan:5}),
...pair("okayama","takamatsu",55,40,"Marine Liner",{green:true,scenic:9,railfan:6}),
...pair("takamatsu","kotohira",55,30,"Dosan Line",{green:false,scenic:7,railfan:4}),
...pair("okayama","matsuyama",160,60,"Limited Express Shiokaze",{green:true,scenic:10,railfan:6}),
...pair("okayama","hiroshima",40,30,"Sanyo Shinkansen",{green:true,scenic:5}),
...pair("hiroshima","miyajimaguchi",32,15,"JR Sanyo Line",{green:false,scenic:7}),
...pair("hiroshima","kokura",50,30,"Sanyo Shinkansen",{green:true,scenic:5}),
...pair("kokura","hakata",18,15,"Sanyo Shinkansen",{green:true,scenic:3}),
...pair("hakata","nagasaki",105,45,"Nishi-Kyushu Shinkansen",{green:true,scenic:7,railfan:5}),
...pair("hakata","kumamoto",40,20,"Kyushu Shinkansen",{green:true,scenic:5}),
...pair("kumamoto","kagoshima",45,30,"Kyushu Shinkansen",{green:true,scenic:7})
];
