// Illustrative planning data only. See docs/data.md.
import { gardenCatalog } from "./gardens.js";
const stop=(id,name,x,y,south,features,values={})=>({id,name,x,y,south,features,endpoint:true,hotel:6,food:6,interest:6,...values});
export const stations=[
stop("sapporo","Sapporo",68,5,-20,["easy-food","arcade","baseball","rainy-day","easy-overnight"],{hotel:10,food:10,interest:9}),
stop("hakodate","Hakodate",64,14,-16,["scenic","seafood","onsen","night-view","easy-overnight"],{hotel:9,food:9,interest:10}),
stop("aomori","Aomori",61,24,-12,["scenic","seafood","apple","railfan","onsen"],{hotel:7,food:8,interest:8}),
stop("hirosaki","Hirosaki",58,26,-11,["castle","apple","scenic","easy-food"],{hotel:7,food:7,interest:8}),
stop("goshogawara","Goshogawara",54,25,-11,["railfan","scenic","goblin"],{hotel:6,food:6,interest:7}),
stop("fukaura","Fukaura",49,27,-10,["sea","scenic","railfan"],{hotel:5,food:5,interest:8}),
stop("higashinoshiro","Higashi-Noshiro",49,30,-9,["sea","scenic","railfan"],{hotel:5,food:5,interest:6}),
stop("akita","Akita",53,30,-9,["goblin","sake","rainy-day","easy-food","railfan"],{hotel:7,food:8,interest:7}),
stop("morioka","Morioka",67,31,-9,["easy-food","noodles","onsen","easy-overnight"],{hotel:7,food:8,interest:7}),
stop("mito","Mito",79,46,-7,["quiet","scenic","easy-food"],{hotel:7,food:7,interest:9}),
stop("sendai","Sendai",72,40,-5,["baseball","arcade","easy-food","nightlife","easy-overnight"],{hotel:9,food:9,interest:9}),
stop("niigata","Niigata",51,40,-5,["sake","seafood","rainy-day","easy-food","easy-overnight"],{hotel:8,food:9,interest:8}),
stop("yamagata","Yamagata",65,42,-4,["onsen","fruit","quiet","scenic","easy-overnight"],{hotel:7,food:7,interest:7}),
stop("nagano","Nagano",57,47,-2,["onsen","mountains","quiet","scenic","easy-overnight"],{hotel:7,food:7,interest:7}),
stop("matsumoto","Matsumoto",57,52,0,["castle","scenic","mountains","easy-food"],{hotel:7,food:7,interest:9}),
stop("kiso_fukushima","Kiso-Fukushima",53,57,2,["scenic","mountains","quiet","railfan"],{hotel:5,food:6,interest:7}),
stop("kanazawa","Kanazawa",38,49,0,["seafood","coffee","easy-food","rainy-day"],{hotel:8,food:9,interest:9}),
stop("nanao","Nanao",35,45,-1,["sea","scenic","easy-food"],{hotel:6,food:7,interest:7}),
stop("wakura_onsen","Wakura Onsen",34,43,-1,["onsen","sea","scenic"],{hotel:7,food:7,interest:8}),
stop("anamizu","Anamizu",31,40,-2,["sea","scenic","railfan","quiet"],{hotel:5,food:5,interest:7}),
stop("toyama","Toyama",47,42,-1,["scenic","seafood","mountains","railfan","easy-overnight"],{hotel:7,food:7,interest:7}),
stop("takayama","Takayama",49,53,2,["scenic","mountains","old-town","easy-food"],{hotel:8,food:8,interest:9}),
stop("gero","Gero",49,60,4,["onsen","scenic","mountains"],{hotel:7,food:7,interest:8}),
stop("gifu","Gifu",46,66,5,["castle","river","easy-food"],{hotel:7,food:7,interest:7}),
stop("nagoya","Nagoya",48,69,6,["baseball","arcade","easy-food","railfan","easy-overnight"],{hotel:9,food:9,interest:9}),
stop("fukui","Fukui",34,55,2,["dinosaur","quiet","soba","goblin","easy-overnight"],{hotel:6,food:7,interest:7}),
stop("tsuruga","Tsuruga",30,59,3,["railfan","seafood","goblin","easy-food","easy-overnight"],{hotel:6,food:7,interest:7}),
stop("karuizawa","Karuizawa",61,53,-1,["coffee","scenic","quiet","easy-food"],{hotel:8,food:8,interest:8}),
stop("tokyo","Tokyo",76,54,-3,["arcade","baseball","easy-food","nightlife","easy-overnight"],{hotel:10,food:10,interest:10}),
stop("yokohama","Yokohama",75,59,-2,["sea","coffee","easy-food","easy-overnight"],{hotel:9,food:9,interest:9}),
stop("kamakura","Kamakura",73,65,0,["sea","temple","scenic","coffee","easy-food"],{hotel:7,food:8,interest:10}),
stop("maibara","Maibara",38,65,5,["quiet","railfan"],{hotel:5,food:5,interest:5}),
stop("kyoto","Kyoto",33,70,7,["temple","coffee","easy-food","nightlife"],{hotel:10,food:10,interest:10}),
stop("nara","Nara",36,78,9,["temple","quiet","scenic","easy-food"],{hotel:7,food:7,interest:10}),
stop("osaka","Osaka",27,76,8,["arcade","baseball","easy-food","nightlife","goblin","easy-overnight"],{hotel:10,food:10,interest:10}),
stop("kobe","Kobe",22,78,9,["sea","coffee","night-view","easy-food","baseball"],{hotel:9,food:9,interest:9}),
stop("himeji","Himeji",17,79,10,["castle","easy-food","scenic","easy-overnight"],{hotel:7,food:8,interest:9}),
stop("okayama","Okayama",10,75,11,["castle","easy-food","easy-overnight","railfan"],{hotel:7,food:7,interest:7}),
stop("yasugi","Yasugi",7,69,8,["quiet","art","onsen","scenic"],{hotel:5,food:5,interest:9}),
stop("onomichi","Onomichi",4,78,12,["sea","scenic","goblin","coffee","bike"],{hotel:7,food:8,interest:10}),
stop("takamatsu","Takamatsu",17,89,13,["udon","sea","easy-food","easy-overnight"],{hotel:8,food:9,interest:9}),
stop("tokushima","Tokushima",26,88,13,["sea","scenic","easy-food"],{hotel:7,food:7,interest:7}),
stop("awa_ikeda","Awa-Ikeda",24,93,15,["scenic","mountains","railfan"],{hotel:5,food:5,interest:7}),
stop("kochi","Kochi",26,99,17,["sea","castle","easy-food","scenic"],{hotel:7,food:8,interest:8}),
stop("kubokawa","Kubokawa",22,103,19,["scenic","railfan","quiet"],{hotel:5,food:5,interest:7}),
stop("uwajima","Uwajima",14,101,19,["sea","castle","railfan"],{hotel:6,food:6,interest:7}),
stop("iyo_ozu","Iyo-Ozu",12,97,17,["castle","sea","scenic"],{hotel:6,food:6,interest:8}),
stop("yawatahama","Yawatahama",10,99,18,["sea","scenic","easy-food"],{hotel:5,food:6,interest:7}),
stop("kotohira","Kotohira",23,94,15,["onsen","temple","udon","quiet","goblin"],{hotel:7,food:8,interest:9}),
stop("matsuyama","Matsuyama",9,93,15,["onsen","castle","tram","easy-food","easy-overnight"],{hotel:8,food:8,interest:9}),
stop("hiroshima","Hiroshima",3,70,13,["baseball","easy-food","nightlife","easy-overnight","scenic"],{hotel:9,food:9,interest:9}),
stop("miyajimaguchi","Miyajimaguchi",1,75,14,["sea","temple","scenic","oyster","goblin"],{hotel:5,food:8,interest:9}),
stop("kokura","Kokura",2,84,17,["railfan","castle","easy-food","goblin","easy-overnight"],{hotel:8,food:8,interest:8}),
stop("hakata","Hakata",5,90,19,["baseball","ramen","arcade","easy-food","easy-overnight"],{hotel:10,food:10,interest:10}),
stop("yufuin","Yufuin",8,91,21,["onsen","scenic","mountains"],{hotel:8,food:8,interest:9}),
stop("oita","Oita",9,93,21,["onsen","easy-food","railfan"],{hotel:7,food:7,interest:7}),
stop("beppu","Beppu",9,92,21,["onsen","sea","easy-food"],{hotel:8,food:8,interest:9}),
stop("aso","Aso",13,96,22,["scenic","mountains","railfan"],{hotel:6,food:6,interest:8}),
stop("miyazaki","Miyazaki",18,99,23,["sea","scenic","easy-food"],{hotel:7,food:7,interest:8}),
stop("nobeoka","Nobeoka",14,96,22,["sea","scenic","railfan"],{hotel:6,food:6,interest:7}),
stop("nagasaki","Nagasaki",0,98,20,["tram","sea","scenic","coffee","goblin"],{hotel:8,food:8,interest:10}),
stop("kumamoto","Kumamoto",10,99,21,["castle","ramen","easy-food","easy-overnight"],{hotel:8,food:9,interest:9}),
stop("kagoshima","Kagoshima",17,106,23,["volcano","onsen","scenic","ferry","easy-food"],{hotel:8,food:8,interest:10}),
stop("ibusuki","Ibusuki",18,111,25,["onsen","sea","scenic","railfan"],{hotel:7,food:7,interest:8})
];
const activityProfiles={
  FOOD:{best:"lunch or dinner",duration:"60 min",effort:"easy",reservation:"usually none",fromStation:"station area"},
  BASEBALL:{best:"evening",duration:"3–4 hr",effort:"easy",reservation:"ticket helpful",fromStation:"urban transit"},
  ARCADE:{best:"late afternoon",duration:"1–3 hr",effort:"easy",reservation:"none",fromStation:"station area"},
  HIKING:{best:"morning",duration:"2–5 hr",effort:"active",reservation:"none",fromStation:"local connection"},
  CYCLING:{best:"daytime",duration:"2–5 hr",effort:"active",reservation:"rental helpful",fromStation:"station area"},
  ONSEN:{best:"late afternoon",duration:"1–2 hr",effort:"easy",reservation:"check ahead",fromStation:"local connection"},
  VIEW:{best:"sunset",duration:"90 min",effort:"some walking",reservation:"none",fromStation:"urban transit"},
  SCENIC:{best:"daytime",duration:"90 min",effort:"easy walk",reservation:"none",fromStation:"walkable"},
  default:{best:"flexible",duration:"1–2 hr",effort:"easy",reservation:"check ahead",fromStation:"local connection"}
};
const activity=(kind,name,detail)=>({kind,name,detail,...(activityProfiles[kind]||activityProfiles.default),mapUrl:"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(name+" Japan"),lastReviewed:"2026-09",source:"curated starter data"});
const activityCatalog={
  tokushima:[activity("CULTURE","Awa Odori Kaikan","A local arts stop near the rail interchange."),activity("FOOD","Tokushima ramen","An easy city meal before a slower Shikoku leg.")],
  awa_ikeda:[activity("SCENIC","Yoshino River","A mountain-river pause on the inland route."),activity("RAIL","Dosan Line junction","Choose the Kochi branch or return north.")],
  kochi:[activity("CASTLE","Kochi Castle","An easy city anchor after the Dosan ride."),activity("FOOD","Hirome Market","A flexible dinner close to the city center.")],
  kubokawa:[activity("RAIL","Kubokawa rail junction","Choose the Yodo River route toward Uwajima."),activity("SCENIC","Shimanto River region","Give the landscape time before the next train.")],
  uwajima:[activity("CASTLE","Uwajima Castle","A small city reward after the Yodo Line."),activity("FOOD","Uwajima seafood","A local meal before the Matsuyama connection.")],
  iyo_ozu:[activity("CASTLE","Ozu Castle","A castle-town stop on the Iyo-nada route."),activity("SCENIC","Hiji River","A relaxed river walk after the train.")],
  yawatahama:[activity("SCENIC","Yawatahama harbor","The coast marks a natural turn in the rail day."),activity("FOOD","Yawatahama seafood","A harbor-town meal before riding back.")],
  yufuin:[activity("ONSEN","Yufuin Onsen","Let the slower Kyudai ride lead to a bath."),activity("SCENIC","Kinrinko Lake","A walkable nature pause in the town.")],
  oita:[activity("FOOD","Oita station meal","A useful stop between the coast and inland routes."),activity("ONSEN","Oita city bath","A simple evening after a long rail day.")],
  beppu:[activity("ONSEN","Beppu hot springs","An onsen destination reached by more than one rail path."),activity("SCENIC","Beppu Bay","A sea-facing walk after the ride.")],
  aso:[activity("SCENIC","Aso caldera","Make the mountain railway journey the main event."),activity("FOOD","Aso local lunch","A pause before returning to Kumamoto.")],
  miyazaki:[activity("SCENIC","Miyazaki coast","A coastal ending for a long Kyushu day."),activity("FOOD","Miyazaki chicken","A regional dinner after the train.")],
  nobeoka:[activity("SCENIC","Nobeoka coast","Break a long east-coast railway ride."),activity("FOOD","Nobeoka local meal","A practical small-city stop.")],
  ibusuki:[activity("ONSEN","Ibusuki sand bath","A bath-led reward for the coastal train."),activity("SCENIC","Ibusuki coast","Walk by the water before riding back.")],
  hirosaki:[activity("CASTLE","Hirosaki Castle","A castle-town pause between the inland and coastal routes."),activity("FOOD","Hirosaki apple sweets","Make the railway stop a local snack break.")],
  goshogawara:[activity("RAIL","Tsugaru Railway","A second local-rail possibility from the Gono corridor."),activity("CULTURE","Tachineputa Museum","A vivid indoor stop near the railway day.")],
  fukaura:[activity("SCENIC","Fukaura coast","Pause for the Sea of Japan instead of rushing past it."),activity("FOOD","Fukaura seafood","A small-town meal on a slow coastal day.")],
  higashinoshiro:[activity("RAIL","Gono Line junction","Choose the coastal branch or the Akita connection."),activity("FOOD","Noshiro local meal","A practical pause before the next train.")],
  matsumoto:[activity("CASTLE","Matsumoto Castle","A strong reason to break a Shinano ride."),activity("FOOD","Shinshu soba","A simple station-city meal before the mountains.")],
  kiso_fukushima:[activity("SCENIC","Kiso Valley","Use the railway stop for a slower mountain-valley day."),activity("FOOD","Kiso soba","A local lunch before the next Shinano leg.")],
  nanao:[activity("FOOD","Nanao seafood","A harbor-town pause on the Noto branch."),activity("SCENIC","Nanao waterfront","Walk near the bay before continuing.")],
  wakura_onsen:[activity("ONSEN","Wakura Onsen","Make the bath the destination of a Noto rail day."),activity("SCENIC","Nanao Bay","A waterside pause near the station town.")],
  anamizu:[activity("RAIL","Noto Railway terminus","Let the end of the line be the point of the trip."),activity("SCENIC","Anamizu waterfront","A quiet bay-side turn before riding back.")],
  takayama:[activity("SCENIC","Takayama old town","Walk the historic streets after the Hida ride."),activity("FOOD","Hida regional meal","A satisfying reason to stop in the mountains.")],
  gero:[activity("ONSEN","Gero Onsen","A bath-led stop along the Hida route."),activity("SCENIC","Hida River","Stretch your legs beside the river.")],
  gifu:[activity("CASTLE","Gifu Castle","A castle and river stop before a Hida connection."),activity("FOOD","Gifu station meal","An easy rail junction lunch.")],
  nagoya:[activity("RAIL","Nagoya Station","Choose between the Hida, Shinano and Tokaido corridors."),activity("FOOD","Nagoya regional meal","A hearty start or finish to a rail day.")],
  sapporo:[activity("BASEBALL","ES CON FIELD HOKKAIDO","A day-game side quest and an easy food-heavy evening."),activity("ARCADE","Susukino","Neon, games, ramen, and a no-planning-needed night.")],
  hakodate:[activity("VIEW","Mt. Hakodate","Ride up for the night view, then descend into the old port streets."),activity("FOOD","Morning Market","Seafood breakfast before deciding what comes next.")],
  aomori:[activity("ART","Nebuta Museum WA RASSE","A compact, vivid rainy-day stop directly by the station."),activity("FOOD","Aomori apple sweets","Coffee-and-pastry wandering with a strong local angle.")],
  akita:[activity("CULTURE","Akita Museum of Art","A calm city-center stop with strong indoor appeal."),activity("FOOD","Kiritanpo","A specifically northern, comforting dinner mission.")],
  morioka:[activity("FOOD","Wanko soba","A very particular regional meal with built-in story value."),activity("ONSEN","Tsunagi Onsen","An easy decompression branch from the city.")],
  mito:[activity("CULTURE","Kodokan","The domain school gives Kairakuen useful city context."),activity("FOOD","Mito natto","A local food mission before or after the garden.")],
  sendai:[activity("BASEBALL","Rakuten Mobile Park","A genuinely useful stadium-night endpoint."),activity("FOOD","Gyutan alley","Beef tongue dinner close to the station rhythm.")],
  niigata:[activity("SAKE","Ponshukan","Station sake-tasting arcade: excellent train-day punctuation."),activity("FOOD","Bandai Bridge waterfront","Seafood and a riverside evening walk.")],
  yamagata:[activity("ONSEN","Yamadera","Temple stairs and mountain views when the energy is there."),activity("FOOD","Cherries and fruit parfaits","A seasonal dessert-forward landing.")],
  nagano:[activity("TEMPLE","Zenko-ji","A generous, walkable anchor for an unplanned morning."),activity("FOOD","Shinshu soba","Simple, reliable station-city food.")],
  kanazawa:[activity("FOOD","Omicho Market","Seafood breakfast or a flexible lunch mission.")],
  toyama:[activity("SCENIC","Kansui Park","Water, mountains, and a low-friction evening walk."),activity("FOOD","Toyama Bay sushi","A concrete seafood dinner reason to stop.")],
  fukui:[activity("WEIRD","Fukui Prefectural Dinosaur Museum","A real, delightful reason to take the branch."),activity("FOOD","Echizen soba","Local noodles and a calm station night.")],
  tsuruga:[activity("RAIL","New Hokuriku station","Infrastructure nerdery plus an easy southward reset."),activity("FOOD","Seafood bowl","A short, satisfying harbor-city dinner.")],
  karuizawa:[activity("COFFEE","Old Karuizawa Ginza","Coffee, bakeries, and slow wandering."),activity("SCENIC","Kumoba Pond","A quiet nature loop close to the resort-town core.")],
  tokyo:[activity("ARCADE","Akihabara","Rhythm games, model shops, and late curry."),activity("BASEBALL","Tokyo Dome","A stadium-night option with dense food nearby.")],
  yokohama:[activity("SCENIC","Minato Mirai waterfront","A harbor walk that still leaves room for a garden day."),activity("FOOD","Yokohama Chinatown","A flexible food stop after Sankeien.")],
  kamakura:[activity("SCENIC","Enoden to the water","A small railway adventure with a seaside payoff."),activity("TEMPLE","Great Buddha","A compact, iconic one-way tourist branch.")],
  maibara:[activity("CASTLE","Hikone Castle","A short local branch for a full castle-and-moat afternoon."),activity("CYCLING","Lake Biwa shore","A flat, waterside continuation when the trains have had their turn.")],
  kyoto:[activity("FOOD","Nishiki Market","Snack-forward wandering that does not require a reservation.")],
  nara:[activity("TEMPLE","Todai-ji and Nara Park","A coherent afternoon of deer, temple scale, and walking."),activity("FOOD","Kakinoha-zushi","Portable leaf-wrapped sushi with regional texture.")],
  osaka:[activity("ARCADE","DenDen Town","Rhythm games, arcades, and the exact right kind of late night."),activity("BASEBALL","Hanshin Tigers","A high-energy game night with a very specific local feeling.")],
  kobe:[activity("VIEW","Nunobiki Ropeway","A fast mountain-and-harbor perspective shift."),activity("FOOD","Kobe coffeehouses","A civilized, low-energy dinner-and-coffee landing.")],
  himeji:[activity("CASTLE","Himeji Castle","The castle is close enough to make a one-way stop feel obvious.")],
  okayama:[activity("FOOD","Demi-katsu","Comfort-food dinner before choosing Shikoku or west tomorrow.")],
  yasugi:[activity("ONSEN","Saginoyu Onsen","A calm overnight close to the museum branch."),activity("FOOD","Shimane soba","A regional meal after a long Yakumo ride.")],
  onomichi:[activity("SCENIC","Temple Walk","Hills, lanes, cats, and views over the Inland Sea."),activity("BIKE","Shimanami Kaido start","A branch for when the railway day wants a bicycle sequel.")],
  takamatsu:[activity("FOOD","Sanuki udon","The meal itself is a practical reason to be here.")],
  kotohira:[activity("ONSEN","Kotohira onsen","A proper one-night reward at the end of a branch."),activity("TEMPLE","Konpira-san","A climb with a clear sense of arrival.")],
  matsuyama:[activity("ONSEN","Dogo Onsen","A classic bathhouse endpoint with tram texture."),activity("CASTLE","Matsuyama Castle","Ropeway-or-walk castle hill above town.")],
  hiroshima:[activity("BASEBALL","Mazda Zoom-Zoom Stadium","A real evening event that makes the endpoint feel complete."),activity("FOOD","Okonomiyaki","Layered Hiroshima-style dinner, easy to choose.")],
  miyajimaguchi:[activity("SEA","Ferry to Miyajima","The water crossing is part of the activity, not transit."),activity("FOOD","Oysters and momiji manju","A compact, delicious island branch.")],
  kokura:[activity("RAIL","Kyushu Railway Museum","A serious rail side quest just across the strait."),activity("FOOD","Yaki-udon","An easy local dinner with real origin-story energy.")],
  hakata:[activity("BASEBALL","Fukuoka SoftBank Hawks","A stadium-night endpoint with all-city convenience."),activity("FOOD","Yatai ramen","Late, flexible street-stall ramen energy.")],
  nagasaki:[activity("TRAM","Streetcar wandering","The trams are a gentle way to make the city the activity."),activity("VIEW","Inasayama night view","A dramatic finish to a southern rail day.")],
  kumamoto:[activity("CASTLE","Kumamoto Castle","A major fortress visit with a city-center base.")],
  kagoshima:[activity("FERRY","Sakurajima","A ferry-and-volcano branch that makes tomorrow interesting.")]
};
const activeTravelCatalog={
  sapporo:[activity("HIKING","Mt. Moiwa","A short city-edge summit for a broad view over Sapporo.")],
  hakodate:[activity("HIKING","Mt. Hakodate trails","Walk or ropeway up, then let the night view finish the day.")],
  aomori:[activity("CYCLING","Aomori Bay loop","A low-stakes waterfront spin from the station area.")],
  akita:[activity("CYCLING","Omono River paths","A calm river-side ride when the city needs more air.")],
  morioka:[activity("HIKING","Mt. Iwate foothills","A real mountain day branch from a useful rail city.")],
  sendai:[activity("CYCLING","Matsushima Bay ride","A coastal extension for a day that wants water and islands.")],
  niigata:[activity("CYCLING","Shinano River cycleway","Flat river riding with an easy city return.")],
  yamagata:[activity("HIKING","Yamadera steps","A vertical little pilgrimage with a clear payoff.")],
  nagano:[activity("HIKING","Togakushi trails","Forest-and-shrine hiking from a mountain gateway.")],
  kanazawa:[activity("CYCLING","Asano River lanes","A gentle bike loop through tea-district texture.")],
  toyama:[activity("HIKING","Tateyama approach","A big-mountain continuation when the weather earns it.")],
  fukui:[activity("CYCLING","Kuzuryu River paths","A quieter, lower-traffic reason to linger.")],
  tsuruga:[activity("CYCLING","Kehi coast","Harbor-and-coast riding after the station side quest.")],
  karuizawa:[activity("CYCLING","Karuizawa lanes","The classic relaxed resort-town bicycle afternoon.")],
  tokyo:[activity("CYCLING","Arakawa riverbank","A wide, unhurried escape from central Tokyo.")],
  kamakura:[activity("HIKING","Daibutsu hiking trail","A wooded connector between temples and the big Buddha.")],
  kyoto:[activity("HIKING","Fushimi Inari early","A pre-crowd mountain-shrine climb with a simple rail start.")],
  nara:[activity("HIKING","Kasugayama paths","Temple-country walking just behind Nara Park.")],
  osaka:[activity("CYCLING","Nakanoshima loop","A city-and-river ride between coffee and dinner.")],
  kobe:[activity("HIKING","Nunobiki Falls trail","An immediately accessible mountain path above the station.")],
  himeji:[activity("CYCLING","Castle-town lanes","An easy bike-scale way to connect castle and garden.")],
  okayama:[activity("CYCLING","Kibiji route","A gentle historic-country ride from an easy rail base.")],
  onomichi:[activity("CYCLING","Shimanami Kaido","The canonical bridge-and-island cycling continuation.")],
  takamatsu:[activity("CYCLING","Setouchi coast","A light sea-edge spin between udon stops.")],
  kotohira:[activity("HIKING","Konpira stair climb","The destination itself comes with its own ascent.")],
  matsuyama:[activity("CYCLING","Dogo to the sea","Tram-town cycling with an onsen landing afterward.")],
  hiroshima:[activity("CYCLING","Peace Boulevard","A flat city ride linking central stops and river views.")],
  miyajimaguchi:[activity("HIKING","Misen on Miyajima","Ferry, shrine, and mountain in one small adventure.")],
  kokura:[activity("CYCLING","Kanmon waterfront","Ride the strait-side paths after the railway museum.")],
  hakata:[activity("CYCLING","Naka River to the bay","A loose city ride between food neighborhoods.")],
  nagasaki:[activity("HIKING","Glover hillside walk","Steep lanes, views, and a city that rewards wandering uphill.")],
  kumamoto:[activity("CYCLING","Shirakawa riverbank","An easy urban ride between garden and dinner.")],
  kagoshima:[activity("CYCLING","Sakurajima loop","A ferry-to-volcano bicycle day with proper goblin energy.")]
};
const stay=(kind,title,detail,area,price)=>({kind,title,detail,area,price,mapUrl:"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(area+" hotel Japan"),lastReviewed:"2026-09",source:"curated starter data"});
const specialStay={
  sapporo:["Beer-and-baseball city night","Susukino or the station district makes an easy late dinner and an even easier next morning.","Sapporo Station / Susukino"],
  hakodate:["Harbor-view decompression","Choose the bay or the hot-spring side when the night view is the whole point.","Hakodate Bay / Yunokawa"],
  aomori:["Waterfront northern night","A compact harbor stay keeps the museum, market, and first train neatly together.","Aomori Station waterfront"],
  akita:["Sake-and-rainy-day hideout","A central stay makes a low-key evening feel intentional rather than stranded.","Akita Station / Kawabata"],
  morioka:["Noodle-city reset","Stay central for an unhurried regional dinner before the next long rail leg.","Morioka Station / Odori"],
  mito:["Kairakuen morning base","Stay close to Mito Station so the garden bus remains a simple next-day choice.","Mito Station"],
  sendai:["Stadium-night base","A central hotel leaves room for baseball, arcades, and a calm late return.","Sendai Station / Ichibancho"],
  niigata:["Sake arcade overnight","Stay by the station for a minimal-friction Ponshukan-and-seafood evening.","Niigata Station / Bandai"],
  yamagata:["Mountain branch overnight","A quiet central base leaves you ready for Yamadera or an onsen turn tomorrow.","Yamagata Station"],
  nagano:["Temple-and-mountain morning","A station or Zenko-ji-side room makes an early shrine walk feel easy.","Nagano Station / Zenko-ji"],
  kanazawa:["Garden-and-coffee overnight","Korimbo or the garden side lets you do Kenroku-en before the city wakes up.","Korimbo / Kenrokuen"],
  toyama:["Mountain-window night","A central room keeps the evening park walk and a Tateyama decision open.","Toyama Station / Kansui Park"],
  fukui:["Dinosaur branch sleepover","Stay near the station for a calm noodle dinner and a straightforward museum run.","Fukui Station"],
  tsuruga:["New-station reset","A simple station stay is useful when the rail junction itself is the side quest.","Tsuruga Station"],
  karuizawa:["Slow resort-town night","Old Karuizawa makes a coffee-and-bike day feel like a proper small escape.","Old Karuizawa / Karuizawa Station"],
  tokyo:["Late-night urban base","Pick a dense neighborhood where arcade, curry, and a first train all coexist.","Ikebukuro / Shinagawa"],
  yokohama:["Harbor-and-garden base","A central room gives you time for the Sankeien bus and a relaxed waterfront evening.","Yokohama Station / Sakuragicho"],
  kamakura:["Seaside temple overnight","A small stay near the water buys you a gentler Enoden morning.","Kamakura Station / Yuigahama"],
  maibara:["Lake Biwa reset","A practical base near the station is enough for the castle-or-cycle branch.","Maibara Station / Hikone"],
  kyoto:["Garden-before-crowds stay","Choose a quieter east-side or central base for an early garden start.","Higashiyama / Kyoto Station"],
  nara:["Park-edge quiet night","Sleeping near Nara Park makes the deer-and-temple morning unusually easy.","Nara Park / Kintetsu Nara"],
  osaka:["Goblin-mode city base","Nipponbashi or Namba keeps the rhythm games, food, and late energy close.","Namba / Nipponbashi"],
  kobe:["Harbor-and-mountain split","A central stay lets you choose ropeway, coffeehouse, or waterfront at the last minute.","Sannomiya / Kitano"],
  himeji:["Castle-opening overnight","Stay near the station so the castle can be a fresh-morning decision.","Himeji Station"],
  okayama:["Crossroads comfort night","A station-side base is perfect for garden time before choosing your next branch.","Okayama Station / Korakuen"],
  yasugi:["Museum-and-onsen branch","Saginoyu Onsen makes the museum visit the center of an unhurried overnight.","Saginoyu Onsen / Yasugi Station"],
  onomichi:["Hills-and-harbor sleepover","A waterfront or hillside stay makes the temple walk feel less like a day trip.","Onomichi waterfront"],
  takamatsu:["Garden-and-udon base","A central stay is ideal for Ritsurin at opening and a flexible Shikoku day.","Takamatsu Station / Ritsurin"],
  kotohira:["Onsen reward night","This is the place to trade efficiency for a ryokan, bath, and kaiseki dinner.","Kotohira Onsen"],
  matsuyama:["Tram-and-onsen night","Dogo is the right kind of destination where the hotel can be the activity.","Dogo Onsen"],
  hiroshima:["Baseball-and-dinner city night","Stay central for an easy stadium evening and a proper okonomiyaki dinner.","Hiroshima Station / Hatchobori"],
  miyajimaguchi:["Island-first morning","A ferry-side base gives you the best chance at a quiet Miyajima start.","Miyajimaguchi / Miyajima"],
  kokura:["Rail-museum city reset","A station-side hotel makes the museum, strait, and next shinkansen painless.","Kokura Station"],
  hakata:["Ramen-and-first-train base","Stay by Hakata for an effortless late meal and a clean southern launch.","Hakata Station / Nakasu"],
  nagasaki:["Hillside tram night","A city-center or harbor stay turns the sloped streets into the evening plan.","Nagasaki Station / Dejima"],
  kumamoto:["Castle-city easy night","A central room gives you garden, castle, ramen, and a relaxed morning.","Kumamoto Station / Shimotori"],
  kagoshima:["Volcano-view landing","Choose the central or bay side when the ferry and mountain are tomorrow's plan.","Kagoshima-Chuo / Tenmonkan"]
};
stations.forEach((station)=>{
  const active=activeTravelCatalog[station.id]||[];
  const gardens=gardenCatalog[station.id]||[];
  station.activities=[...(activityCatalog[station.id]||[]),...gardens.map((item)=>({...item})),...active];
  if(gardens.length) station.features.push("garden");
  station.features.push(...active.map((item)=>item.kind==="HIKING"?"hike":"cycle"));
  const [title,detail,area]=specialStay[station.id]||[station.name+" rail-base night","Stay near the station to leave room for the next railway choice.",station.name+" Station"];
  const late=station.features.includes("goblin")||station.features.includes("arcade")||station.features.includes("nightlife");
  station.stays=[
    stay("EASY LANDING","Station-side easy landing","Late check-in, a short walk from the platforms, and a reliable base for an early departure.",station.name+" Station","¥"),
    stay("WORTH THE NIGHT",title,detail,area,"¥¥–¥¥¥"),
    stay(late?"GOBLIN MODE":"CONVENIENCE BASE",late?"Late-night city base":"First-train reset",late?"Choose a dense, walkable pocket so dinner and a small side quest are still possible after the train.":"Keep the room close to the station when tomorrow's connection matters more than the hotel.",station.name+" Station","¥–¥¥")
  ];
  station.activities.forEach((item)=>{ item.mapUrl="https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(item.name+" "+station.name+" Japan"); });
  station.stays.forEach((item)=>{ item.mapUrl="https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(item.area+" "+station.name+" Japan"); });
});
const railProfiles={
  "Iyonada Monogatari / Yosan Line":{rideNote:"A slow Iyo-nada sea-view ride; check operating days and seats.",window:"Keep the sea side in view along the coast.",ekiben:"Arrange food before boarding; onboard meals can require advance booking."},
  "Yodo Line / Shimanto Trolley":{rideNote:"A river-and-mountain local railway day; check trolley dates.",window:"Follow the Shimanto River through the interior.",ekiben:"Bring a meal from Kochi or Uwajima."},
  "Tosa Toki no Yoake no Monogatari":{rideNote:"A leisurely Kochi-to-Kubokawa sightseeing ride; check running dates.",window:"The changing Tosa countryside is the point.",ekiben:"Arrange food before the train if you need it."},
  "Yufuin no Mori / Kyudai Line":{rideNote:"A wooded inland crossing toward Yufuin; reserve and check the train.",window:"Watch the valleys open on the Kyudai route.",ekiben:"Hakata makes an easy boarding-food stop."},
  "Ibusuki no Tamatebako":{rideNote:"A coastal ride to an onsen terminus; seats are reserved.",window:"Look for sea views on the Satsuma Peninsula.",ekiben:"Stock up in Kagoshima-Chuo before leaving."},
  "Hohi Main Line / Aso Boy":{rideNote:"A mountain route toward the Aso caldera; check sightseeing-train days.",window:"The volcanic landscape is the main event.",ekiben:"Kumamoto is a practical food stop."},
  "Limited Express Hida":{rideNote:"The Hida River and mountain country make the ride the activity.",window:"Look for river bends and deep valleys on the Takayama route.",ekiben:"Nagoya or Toyama is a sensible food stop before boarding."},
  "Limited Express Shinano":{rideNote:"A winding Kiso Valley route linking city and mountain rail hubs.",window:"Watch the mountain valleys between Nagoya and Matsumoto.",ekiben:"Pick up food at Nagoya, Matsumoto, or Nagano."},
  "Resort Shirakami / Gono Line":{rideNote:"A slow Sea of Japan railway day; check running dates and seat reservations.",window:"The coast and Shirakami mountains are the main event.",ekiben:"Stock up in Akita or Aomori before the long ride."},
  "Nanao Line / Noto Kagaribi":{rideNote:"Leave Kanazawa for the Noto Peninsula and Nanao Bay.",window:"Watch the landscape open toward the bay.",ekiben:"Kanazawa is a reliable place to bring food."},
  "Noto Railway":{rideNote:"A local line where the terminus can be the whole point.",window:"Look for bay views along the Noto branch.",ekiben:"Bring food from Nanao or Wakura Onsen."},
  "Hokuriku Shinkansen":{rideNote:"Fast north-country reach for a very different kind of day.",window:"Watch for mountain weather and long valley views.",ekiben:"Kanazawa and Tokyo both make easy ekiben starts."},
  "Tohoku Shinkansen":{rideNote:"A long, clean line for committing to a bigger geographic shift.",window:"The landscape opens out as the train heads north.",ekiben:"Bring an ekiben for the longer leg."},
  "Hokkaido / Tohoku Shinkansen":{rideNote:"A threshold-crossing ride: mainland to the far north.",window:"Keep an eye out for changing coast and northern light.",ekiben:"Hakodate is an especially good snack reset."},
  "Limited Express Hokuto":{rideNote:"A proper train day with an arrival that feels earned.",window:"Coast, forest, and wide northern skies do the work.",ekiben:"Pick up something substantial before boarding."},
  "Sanyo Shinkansen":{rideNote:"A quick westward leap that leaves room for the destination.",window:"Sit back; this is the efficient connector.",ekiben:"Station bento works well for a short rail lunch."},
  "Marine Liner":{rideNote:"The sea crossing is the reason to take this train.",window:"Cross the Seto Ohashi bridge with water on both sides.",ekiben:"Grab a small snack in Okayama before the crossing."},
  "Limited Express Shiokaze":{rideNote:"A scenic Shikoku branch with a more old-school rail rhythm.",window:"The Seto crossing is the visual reward.",ekiben:"Okayama is the easy place to stock up."},
  "Nishi-Kyushu Shinkansen":{rideNote:"A southern branch that turns the route into the adventure.",window:"The western landscape gets greener and more folded.",ekiben:"Hakata is the reliable boarding-food stop."},
  "Kyushu Shinkansen":{rideNote:"A fast southern extension with room left for side quests.",window:"Look out for the broad, volcanic south-country feel.",ekiben:"Hakata and Kumamoto are useful food stops."},
  "Limited Express Hitachi / Tokiwa":{rideNote:"A direct northeast branch for a garden-led Mito day.",window:"The city thins out as the Joban corridor heads north.",ekiben:"A Tokyo Station snack is an easy start."},
  "Limited Express Yakumo":{rideNote:"A mountain-crossing branch that gives the museum a railway story.",window:"Watch the landscape shift on the Hakubi route.",ekiben:"Okayama is the easy food stop before this longer ride."},
  default:{rideNote:"A useful rail link that keeps the day open.",window:"Take the window seat if the weather is good.",ekiben:"A station snack makes the connection easier."}
};
const railProfile=(line)=>railProfiles[line]||railProfiles.default;
const edge=(from,to,minutes,headway,line,extras={})=>({from,to,minutes,headway,line,confidence:headway>35?"medium":"high",...railProfile(line),...extras});
const pair=(a,b,minutes,headway,line,extras)=>[edge(a,b,minutes,headway,line,extras),edge(b,a,minutes,headway,line,extras)];
export const services=[
...pair("takamatsu","tokushima",75,60,"Kotoku Line",{scenic:8}),
...pair("kotohira","awa_ikeda",65,60,"Dosan Line",{scenic:10,railfan:4}),
...pair("awa_ikeda","kochi",80,60,"Dosan Line",{scenic:12,railfan:4}),
...pair("takamatsu","kochi",135,60,"Limited Express Shimanto",{scenic:12,green:true}),
...pair("okayama","kochi",155,60,"Limited Express Nanpu",{scenic:13,green:true}),
...pair("kochi","kubokawa",110,120,"Tosa Toki no Yoake no Monogatari",{scenic:16,railfan:7,confidence:"medium"}),
...pair("kochi","kubokawa",70,60,"Dosan Line",{scenic:10}),
...pair("kubokawa","uwajima",135,120,"Yodo Line / Shimanto Trolley",{scenic:18,railfan:9,confidence:"medium"}),
...pair("uwajima","matsuyama",80,60,"Limited Express Uwakai",{scenic:9}),
...pair("matsuyama","iyo_ozu",120,120,"Iyonada Monogatari / Yosan Line",{scenic:17,railfan:8,confidence:"medium"}),
...pair("iyo_ozu","yawatahama",90,120,"Iyonada Monogatari / Yosan Line",{scenic:14,railfan:7,confidence:"medium"}),
...pair("matsuyama","yawatahama",140,120,"Iyonada Monogatari / Yosan Line",{scenic:19,railfan:8,confidence:"medium"}),
...pair("iyo_ozu","uwajima",65,60,"Yosan Line",{scenic:9}),
...pair("hakata","yufuin",145,120,"Yufuin no Mori / Kyudai Line",{scenic:17,railfan:7,confidence:"medium"}),
...pair("yufuin","oita",50,120,"Yufuin no Mori / Kyudai Line",{scenic:10,railfan:5,confidence:"medium"}),
...pair("oita","beppu",12,30,"Nippo Main Line",{scenic:4}),
...pair("kokura","beppu",95,30,"Limited Express Sonic",{scenic:8,green:true}),
...pair("hakata","beppu",125,30,"Limited Express Sonic",{scenic:9,green:true}),
...pair("kumamoto","aso",80,90,"Hohi Main Line / Aso Boy",{scenic:15,railfan:7,confidence:"medium"}),
...pair("aso","oita",150,90,"Hohi Main Line",{scenic:15,railfan:5,confidence:"medium"}),
...pair("beppu","nobeoka",115,60,"Nippo Main Line",{scenic:11}),
...pair("nobeoka","miyazaki",80,60,"Nippo Main Line",{scenic:10}),
...pair("miyazaki","kagoshima",140,60,"Nippo Main Line",{scenic:11}),
...pair("kagoshima","ibusuki",55,120,"Ibusuki no Tamatebako",{scenic:14,railfan:6,confidence:"medium"}),
...pair("aomori","hirosaki",40,40,"Ou Main Line",{scenic:5}),
...pair("hirosaki","goshogawara",45,90,"Resort Shirakami / Gono Line",{scenic:11,railfan:6,confidence:"medium"}),
...pair("goshogawara","fukaura",110,120,"Resort Shirakami / Gono Line",{scenic:15,railfan:7,confidence:"medium"}),
...pair("fukaura","higashinoshiro",130,120,"Resort Shirakami / Gono Line",{scenic:16,railfan:7,confidence:"medium"}),
...pair("higashinoshiro","akita",60,60,"Ou Main Line",{scenic:5}),
...pair("aomori","akita",310,180,"Resort Shirakami / Gono Line",{scenic:26,railfan:12,confidence:"medium"}),
...pair("niigata","akita",225,90,"Limited Express Inaho",{scenic:13,railfan:5,confidence:"medium"}),
...pair("nagano","matsumoto",55,60,"Limited Express Shinano",{scenic:8,green:true}),
...pair("matsumoto","kiso_fukushima",80,60,"Limited Express Shinano",{scenic:11,green:true}),
...pair("kiso_fukushima","nagoya",95,60,"Limited Express Shinano",{scenic:10,green:true}),
...pair("nagoya","matsumoto",130,60,"Limited Express Shinano",{scenic:16,green:true}),
...pair("nagoya","nagano",190,60,"Limited Express Shinano",{scenic:20,green:true}),
...pair("nagoya","gifu",25,20,"Tokaido Main Line",{scenic:3}),
...pair("gifu","gero",85,60,"Limited Express Hida",{scenic:11,green:true}),
...pair("gero","takayama",55,60,"Limited Express Hida",{scenic:12,green:true}),
...pair("takayama","toyama",95,120,"Limited Express Hida",{scenic:12,green:true,confidence:"medium"}),
...pair("nagoya","takayama",155,60,"Limited Express Hida",{scenic:19,green:true}),
...pair("nagoya","toyama",245,120,"Limited Express Hida",{scenic:23,green:true,confidence:"medium"}),
...pair("kanazawa","nanao",60,45,"Nanao Line / Noto Kagaribi",{scenic:7,green:true}),
...pair("nanao","wakura_onsen",8,40,"Nanao Line / Noto Kagaribi",{scenic:4}),
...pair("kanazawa","wakura_onsen",68,60,"Nanao Line / Noto Kagaribi",{scenic:10,green:true}),
...pair("wakura_onsen","anamizu",45,60,"Noto Railway",{scenic:11,railfan:7,confidence:"medium"}),
...pair("nanao","anamizu",55,60,"Noto Railway",{scenic:12,railfan:7,confidence:"medium"}),
...pair("nagoya","maibara",30,20,"Tokaido Shinkansen",{green:true,scenic:3}),
...pair("nagoya","tokyo",100,15,"Tokaido Shinkansen",{green:true,scenic:4}),
...pair("sapporo","hakodate",230,60,"Limited Express Hokuto",{green:true,scenic:8}),
...pair("hakodate","aomori",70,60,"Hokkaido / Tohoku Shinkansen",{green:true,scenic:7}),
...pair("aomori","morioka",115,40,"Tohoku Shinkansen",{green:true,scenic:7}),
...pair("morioka","sendai",80,25,"Tohoku Shinkansen",{green:true,scenic:5}),
...pair("sendai","tokyo",95,15,"Tohoku Shinkansen",{green:true,gran:true,scenic:5}),
...pair("tokyo","mito",85,30,"Limited Express Hitachi / Tokiwa",{green:true,scenic:3}),
...pair("akita","morioka",95,60,"Akita Shinkansen",{green:true,scenic:8,railfan:4}),
...pair("yamagata","sendai",75,60,"Senzan Line",{green:false,scenic:8,railfan:4}),
...pair("niigata","tokyo",120,20,"Joetsu Shinkansen",{green:true,scenic:5}),
...pair("nagano","karuizawa",30,30,"Hokuriku Shinkansen",{green:true,scenic:6}),
...pair("karuizawa","tokyo",65,30,"Hokuriku Shinkansen",{green:true,gran:true,scenic:5}),
...pair("tokyo","yokohama",30,10,"Tokaido Line",{green:false,scenic:2}),
...pair("tokyo","kamakura",55,15,"Yokosuka Line",{green:false,scenic:4}),
...pair("yokohama","kamakura",25,15,"Yokosuka Line",{green:false,scenic:4}),
...pair("kanazawa","toyama",22,20,"Hokuriku Shinkansen",{green:true,scenic:4}),
...pair("kanazawa","tsuruga",55,30,"Hokuriku Shinkansen",{green:true,scenic:6}),
...pair("kanazawa","nagano",65,30,"Hokuriku Shinkansen",{green:true,scenic:6}),
...pair("kanazawa","tokyo",155,30,"Hokuriku Shinkansen",{green:true,gran:true,scenic:7}),
...pair("tsuruga","fukui",18,30,"Hokuriku Shinkansen",{green:true,scenic:4}),
...pair("tsuruga","maibara",52,30,"Limited Express",{green:true,scenic:6}),
...pair("maibara","kyoto",20,15,"Tokaido Shinkansen",{green:true,scenic:3}),
...pair("kyoto","osaka",28,15,"JR Kyoto Line",{green:false,scenic:3}),
...pair("kyoto","nara",48,30,"Nara Line",{green:false,scenic:4}),
...pair("osaka","kobe",22,15,"JR Kobe Line",{green:false,scenic:4}),
...pair("osaka","himeji",60,15,"Sanyo Shinkansen",{green:true,scenic:5}),
...pair("himeji","okayama",22,20,"Sanyo Shinkansen",{green:true,scenic:5}),
...pair("okayama","yasugi",140,60,"Limited Express Yakumo",{green:true,scenic:8,railfan:5}),
...pair("okayama","onomichi",65,30,"Sanyo Main Line",{green:false,scenic:8,railfan:5}),
...pair("okayama","takamatsu",55,40,"Marine Liner",{green:true,scenic:9,railfan:6}),
...pair("takamatsu","kotohira",55,30,"Dosan Line",{green:false,scenic:7,railfan:4}),
...pair("okayama","matsuyama",160,60,"Limited Express Shiokaze",{green:true,scenic:10,railfan:6}),
...pair("okayama","hiroshima",40,30,"Sanyo Shinkansen",{green:true,scenic:5}),
...pair("hiroshima","miyajimaguchi",32,15,"JR Sanyo Line",{green:false,scenic:7}),
...pair("hiroshima","kokura",50,30,"Sanyo Shinkansen",{green:true,scenic:5}),
...pair("kokura","hakata",18,15,"Sanyo Shinkansen",{green:true,scenic:3}),
...pair("hakata","nagasaki",105,45,"Nishi-Kyushu Shinkansen",{green:true,scenic:7,railfan:5}),
...pair("hakata","kumamoto",40,20,"Kyushu Shinkansen",{green:true,scenic:5}),
...pair("kumamoto","kagoshima",45,30,"Kyushu Shinkansen",{green:true,scenic:7})
];
