// Illustrative planning data only. See docs/data.md.
const stop=(id,name,x,y,south,features,values={})=>({id,name,x,y,south,features,endpoint:true,hotel:6,food:6,interest:6,...values});
export const stations=[
stop("sapporo","Sapporo",68,5,-20,["easy-food","arcade","baseball","rainy-day","easy-overnight"],{hotel:10,food:10,interest:9}),
stop("hakodate","Hakodate",64,14,-16,["scenic","seafood","onsen","night-view","easy-overnight"],{hotel:9,food:9,interest:10}),
stop("aomori","Aomori",61,24,-12,["scenic","seafood","apple","railfan","onsen"],{hotel:7,food:8,interest:8}),
stop("akita","Akita",53,30,-9,["goblin","sake","rainy-day","easy-food","railfan"],{hotel:7,food:8,interest:7}),
stop("morioka","Morioka",67,31,-9,["easy-food","noodles","onsen","easy-overnight"],{hotel:7,food:8,interest:7}),
stop("sendai","Sendai",72,40,-5,["baseball","arcade","easy-food","nightlife","easy-overnight"],{hotel:9,food:9,interest:9}),
stop("niigata","Niigata",51,40,-5,["sake","seafood","rainy-day","easy-food","easy-overnight"],{hotel:8,food:9,interest:8}),
stop("yamagata","Yamagata",65,42,-4,["onsen","fruit","quiet","scenic","easy-overnight"],{hotel:7,food:7,interest:7}),
stop("nagano","Nagano",57,47,-2,["onsen","mountains","quiet","scenic","easy-overnight"],{hotel:7,food:7,interest:7}),
stop("kanazawa","Kanazawa",38,49,0,["garden","seafood","coffee","easy-food","rainy-day"],{hotel:8,food:9,interest:9}),
stop("toyama","Toyama",47,42,-1,["scenic","seafood","mountains","railfan","easy-overnight"],{hotel:7,food:7,interest:7}),
stop("fukui","Fukui",34,55,2,["dinosaur","quiet","soba","goblin","easy-overnight"],{hotel:6,food:7,interest:7}),
stop("tsuruga","Tsuruga",30,59,3,["railfan","seafood","goblin","easy-food","easy-overnight"],{hotel:6,food:7,interest:7}),
stop("karuizawa","Karuizawa",61,53,-1,["coffee","scenic","quiet","easy-food","garden"],{hotel:8,food:8,interest:8}),
stop("tokyo","Tokyo",76,54,-3,["arcade","baseball","easy-food","nightlife","garden","easy-overnight"],{hotel:10,food:10,interest:10}),
stop("kamakura","Kamakura",73,61,0,["sea","temple","scenic","coffee","easy-food"],{hotel:7,food:8,interest:10}),
stop("maibara","Maibara",38,65,5,["quiet","railfan"],{hotel:5,food:5,interest:5}),
stop("kyoto","Kyoto",33,70,7,["garden","temple","coffee","easy-food","nightlife"],{hotel:10,food:10,interest:10}),
stop("nara","Nara",36,78,9,["temple","garden","quiet","scenic","easy-food"],{hotel:7,food:7,interest:10}),
stop("osaka","Osaka",27,76,8,["arcade","baseball","easy-food","nightlife","goblin","easy-overnight"],{hotel:10,food:10,interest:10}),
stop("kobe","Kobe",22,78,9,["sea","coffee","night-view","easy-food","baseball"],{hotel:9,food:9,interest:9}),
stop("himeji","Himeji",17,79,10,["castle","garden","easy-food","scenic","easy-overnight"],{hotel:7,food:8,interest:9}),
stop("okayama","Okayama",10,75,11,["garden","castle","easy-food","easy-overnight","railfan"],{hotel:7,food:7,interest:7}),
stop("onomichi","Onomichi",4,78,12,["sea","scenic","goblin","coffee","bike"],{hotel:7,food:8,interest:10}),
stop("takamatsu","Takamatsu",17,89,13,["udon","garden","sea","easy-food","easy-overnight"],{hotel:8,food:9,interest:9}),
stop("kotohira","Kotohira",23,94,15,["onsen","temple","udon","quiet","goblin"],{hotel:7,food:8,interest:9}),
stop("matsuyama","Matsuyama",9,93,15,["onsen","castle","tram","easy-food","easy-overnight"],{hotel:8,food:8,interest:9}),
stop("hiroshima","Hiroshima",3,70,13,["baseball","easy-food","nightlife","easy-overnight","scenic"],{hotel:9,food:9,interest:9}),
stop("miyajimaguchi","Miyajimaguchi",1,75,14,["sea","temple","scenic","oyster","goblin"],{hotel:5,food:8,interest:9}),
stop("kokura","Kokura",2,84,17,["railfan","castle","easy-food","goblin","easy-overnight"],{hotel:8,food:8,interest:8}),
stop("hakata","Hakata",5,90,19,["baseball","ramen","arcade","easy-food","easy-overnight"],{hotel:10,food:10,interest:10}),
stop("nagasaki","Nagasaki",0,98,20,["tram","sea","scenic","coffee","goblin"],{hotel:8,food:8,interest:10}),
stop("kumamoto","Kumamoto",10,99,21,["castle","ramen","garden","easy-food","easy-overnight"],{hotel:8,food:9,interest:9}),
stop("kagoshima","Kagoshima",17,106,23,["volcano","onsen","scenic","ferry","easy-food"],{hotel:8,food:8,interest:10})
];
const activityProfiles={
  GARDEN:{best:"morning",duration:"90 min",effort:"easy walk",reservation:"none",fromStation:"short local ride"},
  FOOD:{best:"lunch or dinner",duration:"60 min",effort:"easy",reservation:"usually none",fromStation:"station area"},
  BASEBALL:{best:"evening",duration:"3–4 hr",effort:"easy",reservation:"ticket helpful",fromStation:"urban transit"},
  ARCADE:{best:"late afternoon",duration:"1–3 hr",effort:"easy",reservation:"none",fromStation:"station area"},
  HIKING:{best:"morning",duration:"2–5 hr",effort:"active",reservation:"none",fromStation:"local connection"},
  CYCLING:{best:"daytime",duration:"2–5 hr",effort:"active",reservation:"rental helpful",fromStation:"station area"},
  ONSEN:{best:"late afternoon",duration:"1–2 hr",effort:"easy",reservation:"check ahead",fromStation:"local connection"},
  VIEW:{best:"sunset",duration:"90 min",effort:"some walking",reservation:"none",fromStation:"urban transit"},
  SCENIC:{best:"daytime",duration:"90 min",effort:"easy walk",reservation:"none",fromStation:"walkable"},
  default:{best:"flexible",duration:"1–2 hr",effort:"easy",reservation:"check ahead",fromStation:"local connection"}
};
const activity=(kind,name,detail)=>({kind,name,detail,...(activityProfiles[kind]||activityProfiles.default),mapUrl:"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(name+" Japan"),lastReviewed:"2026-09",source:"curated starter data"});
const activityCatalog={
  sapporo:[activity("BASEBALL","ES CON FIELD HOKKAIDO","A day-game side quest and an easy food-heavy evening."),activity("ARCADE","Susukino","Neon, games, ramen, and a no-planning-needed night.")],
  hakodate:[activity("VIEW","Mt. Hakodate","Ride up for the night view, then descend into the old port streets."),activity("FOOD","Morning Market","Seafood breakfast before deciding what comes next.")],
  aomori:[activity("ART","Nebuta Museum WA RASSE","A compact, vivid rainy-day stop directly by the station."),activity("FOOD","Aomori apple sweets","Coffee-and-pastry wandering with a strong local angle.")],
  akita:[activity("CULTURE","Akita Museum of Art","A calm city-center stop with strong indoor appeal."),activity("FOOD","Kiritanpo","A specifically northern, comforting dinner mission.")],
  morioka:[activity("FOOD","Wanko soba","A very particular regional meal with built-in story value."),activity("ONSEN","Tsunagi Onsen","An easy decompression branch from the city.")],
  sendai:[activity("BASEBALL","Rakuten Mobile Park","A genuinely useful stadium-night endpoint."),activity("FOOD","Gyutan alley","Beef tongue dinner close to the station rhythm.")],
  niigata:[activity("SAKE","Ponshukan","Station sake-tasting arcade: excellent train-day punctuation."),activity("FOOD","Bandai Bridge waterfront","Seafood and a riverside evening walk.")],
  yamagata:[activity("ONSEN","Yamadera","Temple stairs and mountain views when the energy is there."),activity("FOOD","Cherries and fruit parfaits","A seasonal dessert-forward landing.")],
  nagano:[activity("TEMPLE","Zenko-ji","A generous, walkable anchor for an unplanned morning."),activity("FOOD","Shinshu soba","Simple, reliable station-city food.")],
  kanazawa:[activity("GARDEN","Kenroku-en","Arrive at opening; coffee by the big pond afterwards."),activity("FOOD","Omicho Market","Seafood breakfast or a flexible lunch mission.")],
  toyama:[activity("SCENIC","Kansui Park","Water, mountains, and a low-friction evening walk."),activity("FOOD","Toyama Bay sushi","A concrete seafood dinner reason to stop.")],
  fukui:[activity("WEIRD","Fukui Prefectural Dinosaur Museum","A real, delightful reason to take the branch."),activity("FOOD","Echizen soba","Local noodles and a calm station night.")],
  tsuruga:[activity("RAIL","New Hokuriku station","Infrastructure nerdery plus an easy southward reset."),activity("FOOD","Seafood bowl","A short, satisfying harbor-city dinner.")],
  karuizawa:[activity("COFFEE","Old Karuizawa Ginza","Coffee, bakeries, and slow wandering."),activity("SCENIC","Kumoba Pond","A quiet nature loop close to the resort-town core.")],
  tokyo:[activity("ARCADE","Akihabara","Rhythm games, model shops, and late curry."),activity("BASEBALL","Tokyo Dome","A stadium-night option with dense food nearby.")],
  kamakura:[activity("SCENIC","Enoden to the water","A small railway adventure with a seaside payoff."),activity("TEMPLE","Great Buddha","A compact, iconic one-way tourist branch.")],
  maibara:[activity("CASTLE","Hikone Castle","A short local branch for a full castle-and-moat afternoon."),activity("CYCLING","Lake Biwa shore","A flat, waterside continuation when the trains have had their turn.")],
  kyoto:[activity("GARDEN","Murin-an","A quieter garden counterweight to the big headline sites."),activity("FOOD","Nishiki Market","Snack-forward wandering that does not require a reservation.")],
  nara:[activity("TEMPLE","Todai-ji and Nara Park","A coherent afternoon of deer, temple scale, and walking."),activity("FOOD","Kakinoha-zushi","Portable leaf-wrapped sushi with regional texture.")],
  osaka:[activity("ARCADE","DenDen Town","Rhythm games, arcades, and the exact right kind of late night."),activity("BASEBALL","Hanshin Tigers","A high-energy game night with a very specific local feeling.")],
  kobe:[activity("VIEW","Nunobiki Ropeway","A fast mountain-and-harbor perspective shift."),activity("FOOD","Kobe coffeehouses","A civilized, low-energy dinner-and-coffee landing.")],
  himeji:[activity("CASTLE","Himeji Castle","The castle is close enough to make a one-way stop feel obvious."),activity("GARDEN","Koko-en","A garden pair that makes the castle day breathe.")],
  okayama:[activity("GARDEN","Koraku-en","A major garden directly useful to a rail itinerary."),activity("FOOD","Demi-katsu","Comfort-food dinner before choosing Shikoku or west tomorrow.")],
  onomichi:[activity("SCENIC","Temple Walk","Hills, lanes, cats, and views over the Inland Sea."),activity("BIKE","Shimanami Kaido start","A branch for when the railway day wants a bicycle sequel.")],
  takamatsu:[activity("GARDEN","Ritsurin Garden","An opening-time garden with an easy city landing."),activity("FOOD","Sanuki udon","The meal itself is a practical reason to be here.")],
  kotohira:[activity("ONSEN","Kotohira onsen","A proper one-night reward at the end of a branch."),activity("TEMPLE","Konpira-san","A climb with a clear sense of arrival.")],
  matsuyama:[activity("ONSEN","Dogo Onsen","A classic bathhouse endpoint with tram texture."),activity("CASTLE","Matsuyama Castle","Ropeway-or-walk castle hill above town.")],
  hiroshima:[activity("BASEBALL","Mazda Zoom-Zoom Stadium","A real evening event that makes the endpoint feel complete."),activity("FOOD","Okonomiyaki","Layered Hiroshima-style dinner, easy to choose.")],
  miyajimaguchi:[activity("SEA","Ferry to Miyajima","The water crossing is part of the activity, not transit."),activity("FOOD","Oysters and momiji manju","A compact, delicious island branch.")],
  kokura:[activity("RAIL","Kyushu Railway Museum","A serious rail side quest just across the strait."),activity("FOOD","Yaki-udon","An easy local dinner with real origin-story energy.")],
  hakata:[activity("BASEBALL","Fukuoka SoftBank Hawks","A stadium-night endpoint with all-city convenience."),activity("FOOD","Yatai ramen","Late, flexible street-stall ramen energy.")],
  nagasaki:[activity("TRAM","Streetcar wandering","The trams are a gentle way to make the city the activity."),activity("VIEW","Inasayama night view","A dramatic finish to a southern rail day.")],
  kumamoto:[activity("CASTLE","Kumamoto Castle","A major fortress visit with a city-center base."),activity("GARDEN","Suizenji Jojuen","A compact garden reset after the castle.")],
  kagoshima:[activity("GARDEN","Sengan-en","Garden, volcano view, and a deeply specific southern landing."),activity("FERRY","Sakurajima","A ferry-and-volcano branch that makes tomorrow interesting.")]
};
const activeTravelCatalog={
  sapporo:[activity("HIKING","Mt. Moiwa","A short city-edge summit for a broad view over Sapporo.")],
  hakodate:[activity("HIKING","Mt. Hakodate trails","Walk or ropeway up, then let the night view finish the day.")],
  aomori:[activity("CYCLING","Aomori Bay loop","A low-stakes waterfront spin from the station area.")],
  akita:[activity("CYCLING","Omono River paths","A calm river-side ride when the city needs more air.")],
  morioka:[activity("HIKING","Mt. Iwate foothills","A real mountain day branch from a useful rail city.")],
  sendai:[activity("CYCLING","Matsushima Bay ride","A coastal extension for a day that wants water and islands.")],
  niigata:[activity("CYCLING","Shinano River cycleway","Flat river riding with an easy city return.")],
  yamagata:[activity("HIKING","Yamadera steps","A vertical little pilgrimage with a clear payoff.")],
  nagano:[activity("HIKING","Togakushi trails","Forest-and-shrine hiking from a mountain gateway.")],
  kanazawa:[activity("CYCLING","Asano River lanes","A gentle bike loop through tea-district texture.")],
  toyama:[activity("HIKING","Tateyama approach","A big-mountain continuation when the weather earns it.")],
  fukui:[activity("CYCLING","Kuzuryu River paths","A quieter, lower-traffic reason to linger.")],
  tsuruga:[activity("CYCLING","Kehi coast","Harbor-and-coast riding after the station side quest.")],
  karuizawa:[activity("CYCLING","Karuizawa lanes","The classic relaxed resort-town bicycle afternoon.")],
  tokyo:[activity("CYCLING","Arakawa riverbank","A wide, unhurried escape from central Tokyo.")],
  kamakura:[activity("HIKING","Daibutsu hiking trail","A wooded connector between temples and the big Buddha.")],
  kyoto:[activity("HIKING","Fushimi Inari early","A pre-crowd mountain-shrine climb with a simple rail start.")],
  nara:[activity("HIKING","Kasugayama paths","Temple-country walking just behind Nara Park.")],
  osaka:[activity("CYCLING","Nakanoshima loop","A city-and-river ride between coffee and dinner.")],
  kobe:[activity("HIKING","Nunobiki Falls trail","An immediately accessible mountain path above the station.")],
  himeji:[activity("CYCLING","Castle-town lanes","An easy bike-scale way to connect castle and garden.")],
  okayama:[activity("CYCLING","Kibiji route","A gentle historic-country ride from an easy rail base.")],
  onomichi:[activity("CYCLING","Shimanami Kaido","The canonical bridge-and-island cycling continuation.")],
  takamatsu:[activity("CYCLING","Setouchi coast","A light sea-edge spin between udon stops.")],
  kotohira:[activity("HIKING","Konpira stair climb","The destination itself comes with its own ascent.")],
  matsuyama:[activity("CYCLING","Dogo to the sea","Tram-town cycling with an onsen landing afterward.")],
  hiroshima:[activity("CYCLING","Peace Boulevard","A flat city ride linking central stops and river views.")],
  miyajimaguchi:[activity("HIKING","Misen on Miyajima","Ferry, shrine, and mountain in one small adventure.")],
  kokura:[activity("CYCLING","Kanmon waterfront","Ride the strait-side paths after the railway museum.")],
  hakata:[activity("CYCLING","Naka River to the bay","A loose city ride between food neighborhoods.")],
  nagasaki:[activity("HIKING","Glover hillside walk","Steep lanes, views, and a city that rewards wandering uphill.")],
  kumamoto:[activity("CYCLING","Shirakawa riverbank","An easy urban ride between garden and dinner.")],
  kagoshima:[activity("CYCLING","Sakurajima loop","A ferry-to-volcano bicycle day with proper goblin energy.")]
};
const stay=(kind,title,detail,area,price)=>({kind,title,detail,area,price,mapUrl:"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(area+" hotel Japan"),lastReviewed:"2026-09",source:"curated starter data"});
const specialStay={
  sapporo:["Beer-and-baseball city night","Susukino or the station district makes an easy late dinner and an even easier next morning.","Sapporo Station / Susukino"],
  hakodate:["Harbor-view decompression","Choose the bay or the hot-spring side when the night view is the whole point.","Hakodate Bay / Yunokawa"],
  aomori:["Waterfront northern night","A compact harbor stay keeps the museum, market, and first train neatly together.","Aomori Station waterfront"],
  akita:["Sake-and-rainy-day hideout","A central stay makes a low-key evening feel intentional rather than stranded.","Akita Station / Kawabata"],
  morioka:["Noodle-city reset","Stay central for an unhurried regional dinner before the next long rail leg.","Morioka Station / Odori"],
  sendai:["Stadium-night base","A central hotel leaves room for baseball, arcades, and a calm late return.","Sendai Station / Ichibancho"],
  niigata:["Sake arcade overnight","Stay by the station for a minimal-friction Ponshukan-and-seafood evening.","Niigata Station / Bandai"],
  yamagata:["Mountain branch overnight","A quiet central base leaves you ready for Yamadera or an onsen turn tomorrow.","Yamagata Station"],
  nagano:["Temple-and-mountain morning","A station or Zenko-ji-side room makes an early shrine walk feel easy.","Nagano Station / Zenko-ji"],
  kanazawa:["Garden-and-coffee overnight","Korimbo or the garden side lets you do Kenroku-en before the city wakes up.","Korimbo / Kenrokuen"],
  toyama:["Mountain-window night","A central room keeps the evening park walk and a Tateyama decision open.","Toyama Station / Kansui Park"],
  fukui:["Dinosaur branch sleepover","Stay near the station for a calm noodle dinner and a straightforward museum run.","Fukui Station"],
  tsuruga:["New-station reset","A simple station stay is useful when the rail junction itself is the side quest.","Tsuruga Station"],
  karuizawa:["Slow resort-town night","Old Karuizawa makes a coffee-and-bike day feel like a proper small escape.","Old Karuizawa / Karuizawa Station"],
  tokyo:["Late-night urban base","Pick a dense neighborhood where arcade, curry, and a first train all coexist.","Ikebukuro / Shinagawa"],
  kamakura:["Seaside temple overnight","A small stay near the water buys you a gentler Enoden morning.","Kamakura Station / Yuigahama"],
  maibara:["Lake Biwa reset","A practical base near the station is enough for the castle-or-cycle branch.","Maibara Station / Hikone"],
  kyoto:["Garden-before-crowds stay","Choose a quieter east-side or central base for an early garden start.","Higashiyama / Kyoto Station"],
  nara:["Park-edge quiet night","Sleeping near Nara Park makes the deer-and-temple morning unusually easy.","Nara Park / Kintetsu Nara"],
  osaka:["Goblin-mode city base","Nipponbashi or Namba keeps the rhythm games, food, and late energy close.","Namba / Nipponbashi"],
  kobe:["Harbor-and-mountain split","A central stay lets you choose ropeway, coffeehouse, or waterfront at the last minute.","Sannomiya / Kitano"],
  himeji:["Castle-opening overnight","Stay near the station so the castle can be a fresh-morning decision.","Himeji Station"],
  okayama:["Crossroads comfort night","A station-side base is perfect for garden time before choosing your next branch.","Okayama Station / Korakuen"],
  onomichi:["Hills-and-harbor sleepover","A waterfront or hillside stay makes the temple walk feel less like a day trip.","Onomichi waterfront"],
  takamatsu:["Garden-and-udon base","A central stay is ideal for Ritsurin at opening and a flexible Shikoku day.","Takamatsu Station / Ritsurin"],
  kotohira:["Onsen reward night","This is the place to trade efficiency for a ryokan, bath, and kaiseki dinner.","Kotohira Onsen"],
  matsuyama:["Tram-and-onsen night","Dogo is the right kind of destination where the hotel can be the activity.","Dogo Onsen"],
  hiroshima:["Baseball-and-dinner city night","Stay central for an easy stadium evening and a proper okonomiyaki dinner.","Hiroshima Station / Hatchobori"],
  miyajimaguchi:["Island-first morning","A ferry-side base gives you the best chance at a quiet Miyajima start.","Miyajimaguchi / Miyajima"],
  kokura:["Rail-museum city reset","A station-side hotel makes the museum, strait, and next shinkansen painless.","Kokura Station"],
  hakata:["Ramen-and-first-train base","Stay by Hakata for an effortless late meal and a clean southern launch.","Hakata Station / Nakasu"],
  nagasaki:["Hillside tram night","A city-center or harbor stay turns the sloped streets into the evening plan.","Nagasaki Station / Dejima"],
  kumamoto:["Castle-city easy night","A central room gives you garden, castle, ramen, and a relaxed morning.","Kumamoto Station / Shimotori"],
  kagoshima:["Volcano-view landing","Choose the central or bay side when the ferry and mountain are tomorrow's plan.","Kagoshima-Chuo / Tenmonkan"]
};
stations.forEach((station)=>{
  const active=activeTravelCatalog[station.id]||[];
  station.activities=[...(activityCatalog[station.id]||[]),...active];
  station.features.push(...active.map((item)=>item.kind==="HIKING"?"hike":"cycle"));
  const [title,detail,area]=specialStay[station.id];
  const late=station.features.includes("goblin")||station.features.includes("arcade")||station.features.includes("nightlife");
  station.stays=[
    stay("EASY LANDING","Station-side easy landing","Late check-in, a short walk from the platforms, and a reliable base for an early departure.",station.name+" Station","¥"),
    stay("WORTH THE NIGHT",title,detail,area,"¥¥–¥¥¥"),
    stay(late?"GOBLIN MODE":"CONVENIENCE BASE",late?"Late-night city base":"First-train reset",late?"Choose a dense, walkable pocket so dinner and a small side quest are still possible after the train.":"Keep the room close to the station when tomorrow's connection matters more than the hotel.",station.name+" Station","¥–¥¥")
  ];
  station.activities.forEach((item)=>{ item.mapUrl="https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(item.name+" "+station.name+" Japan"); });
  station.stays.forEach((item)=>{ item.mapUrl="https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(item.area+" "+station.name+" Japan"); });
});
const railProfiles={
  "Hokuriku Shinkansen":{rideNote:"Fast north-country reach for a very different kind of day.",window:"Watch for mountain weather and long valley views.",ekiben:"Kanazawa and Tokyo both make easy ekiben starts."},
  "Tohoku Shinkansen":{rideNote:"A long, clean line for committing to a bigger geographic shift.",window:"The landscape opens out as the train heads north.",ekiben:"Bring an ekiben for the longer leg."},
  "Hokkaido / Tohoku Shinkansen":{rideNote:"A threshold-crossing ride: mainland to the far north.",window:"Keep an eye out for changing coast and northern light.",ekiben:"Hakodate is an especially good snack reset."},
  "Limited Express Hokuto":{rideNote:"A proper train day with an arrival that feels earned.",window:"Coast, forest, and wide northern skies do the work.",ekiben:"Pick up something substantial before boarding."},
  "Sanyo Shinkansen":{rideNote:"A quick westward leap that leaves room for the destination.",window:"Sit back; this is the efficient connector.",ekiben:"Station bento works well for a short rail lunch."},
  "Marine Liner":{rideNote:"The sea crossing is the reason to take this train.",window:"Cross the Seto Ohashi bridge with water on both sides.",ekiben:"Grab a small snack in Okayama before the crossing."},
  "Limited Express Shiokaze":{rideNote:"A scenic Shikoku branch with a more old-school rail rhythm.",window:"The Seto crossing is the visual reward.",ekiben:"Okayama is the easy place to stock up."},
  "Nishi-Kyushu Shinkansen":{rideNote:"A southern branch that turns the route into the adventure.",window:"The western landscape gets greener and more folded.",ekiben:"Hakata is the reliable boarding-food stop."},
  "Kyushu Shinkansen":{rideNote:"A fast southern extension with room left for side quests.",window:"Look out for the broad, volcanic south-country feel.",ekiben:"Hakata and Kumamoto are useful food stops."},
  default:{rideNote:"A useful rail link that keeps the day open.",window:"Take the window seat if the weather is good.",ekiben:"A station snack makes the connection easier."}
};
const railProfile=(line)=>railProfiles[line]||railProfiles.default;
const edge=(from,to,minutes,headway,line,extras={})=>({from,to,minutes,headway,line,confidence:headway>35?"medium":"high",...railProfile(line),...extras});
const pair=(a,b,minutes,headway,line,extras)=>[edge(a,b,minutes,headway,line,extras),edge(b,a,minutes,headway,line,extras)];
export const services=[
...pair("sapporo","hakodate",230,60,"Limited Express Hokuto",{green:true,scenic:8}),
...pair("hakodate","aomori",70,60,"Hokkaido / Tohoku Shinkansen",{green:true,scenic:7}),
...pair("aomori","morioka",115,40,"Tohoku Shinkansen",{green:true,scenic:7}),
...pair("morioka","sendai",80,25,"Tohoku Shinkansen",{green:true,scenic:5}),
...pair("sendai","tokyo",95,15,"Tohoku Shinkansen",{green:true,gran:true,scenic:5}),
...pair("akita","morioka",95,60,"Akita Shinkansen",{green:true,scenic:8,railfan:4}),
...pair("yamagata","sendai",75,60,"Senzan Line",{green:false,scenic:8,railfan:4}),
...pair("niigata","tokyo",120,20,"Joetsu Shinkansen",{green:true,scenic:5}),
...pair("nagano","karuizawa",30,30,"Hokuriku Shinkansen",{green:true,scenic:6}),
...pair("karuizawa","tokyo",65,30,"Hokuriku Shinkansen",{green:true,gran:true,scenic:5}),
...pair("kanazawa","toyama",22,20,"Hokuriku Shinkansen",{green:true,scenic:4}),
...pair("kanazawa","tsuruga",55,30,"Hokuriku Shinkansen",{green:true,scenic:6}),
...pair("kanazawa","nagano",65,30,"Hokuriku Shinkansen",{green:true,scenic:6}),
...pair("kanazawa","tokyo",155,30,"Hokuriku Shinkansen",{green:true,gran:true,scenic:7}),
...pair("tsuruga","fukui",18,30,"Hokuriku Shinkansen",{green:true,scenic:4}),
...pair("tsuruga","maibara",52,30,"Limited Express",{green:true,scenic:6}),
...pair("maibara","kyoto",20,15,"Tokaido Shinkansen",{green:true,scenic:3}),
...pair("kyoto","osaka",28,15,"JR Kyoto Line",{green:false,scenic:3}),
...pair("kyoto","nara",48,30,"Nara Line",{green:false,scenic:4}),
...pair("osaka","kobe",22,15,"JR Kobe Line",{green:false,scenic:4}),
...pair("osaka","himeji",60,15,"Sanyo Shinkansen",{green:true,scenic:5}),
...pair("himeji","okayama",22,20,"Sanyo Shinkansen",{green:true,scenic:5}),
...pair("okayama","onomichi",65,30,"Sanyo Main Line",{green:false,scenic:8,railfan:5}),
...pair("okayama","takamatsu",55,40,"Marine Liner",{green:true,scenic:9,railfan:6}),
...pair("takamatsu","kotohira",55,30,"Dosan Line",{green:false,scenic:7,railfan:4}),
...pair("okayama","matsuyama",160,60,"Limited Express Shiokaze",{green:true,scenic:10,railfan:6}),
...pair("okayama","hiroshima",40,30,"Sanyo Shinkansen",{green:true,scenic:5}),
...pair("hiroshima","miyajimaguchi",32,15,"JR Sanyo Line",{green:false,scenic:7}),
...pair("hiroshima","kokura",50,30,"Sanyo Shinkansen",{green:true,scenic:5}),
...pair("kokura","hakata",18,15,"Sanyo Shinkansen",{green:true,scenic:3}),
...pair("hakata","nagasaki",105,45,"Nishi-Kyushu Shinkansen",{green:true,scenic:7,railfan:5}),
...pair("hakata","kumamoto",40,20,"Kyushu Shinkansen",{green:true,scenic:5}),
...pair("kumamoto","kagoshima",45,30,"Kyushu Shinkansen",{green:true,scenic:7})
];
